global:
  envName: dev
  domain: dev.staging.mydomain.dev
  aws:
    s3Bucket: ""
    sqsPrefix: ""
  db:
    mode: pod
  redis:
    mode: pod

image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

resources: {}
